# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1bc49207f457205ca17762b5c6d05375"
name = "extensions-app"
handle = "extensions-app-10"
application_url = "https://homework-costa-months-hide.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "reda-ext.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://homework-costa-months-hide.trycloudflare.com/auth/callback",
  "https://homework-costa-months-hide.trycloudflare.com/auth/shopify/callback",
  "https://homework-costa-months-hide.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
